version: '3.8'
services:
  application:
    build: .
    environment:
      MONGODB_HOST: mongodb
      NUMBER: 4
    volumes:
      - "/Users/anndemo/PycharmProjects/dockerMongo:/app"
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
volumes:
  mongodb_volume: